### ISSUE TITLE
Assistance with Markbot Errors

### ISSUE THREAD

**Issue by breecousineau** [breecousineau/accessible-content-for-all#1]
Hi @wendywarren !

Thank you for class today! I was just wondering if you could help me with these 3 errors Markbot is giving me, I'm not sure I understand what it is asking me to do

Thank you!

Bree

<img width="803" alt="Screen Shot 2022-02-14 at 11 24 00 AM" src="https://user-images.githubusercontent.com/97452245/153905131-e490d9af-ec23-4e31-b22f-7ae3d8d68d29.png">

**Comment by wendywarren** [comment]
Hi @breecousineau,

Markbot is looking for specific accessibility requirements. 

The first one is referring to landmark roles. Users with screen readers make use of landmark roles so that they can access parts of our page quickly. There is an html element where we would assign the role of "contentinfo". 

Here is a list of commonly used landmark roles and where you would place them: 

https://learn-the-web.algonquindesign.ca/topics/content-accessibility/#landmark-roles

The second issue is referring to using 'id' when creating jump links. The `<nav>` has three topics which match three sections within the content. We can use jump links to take the user to that content from the `<nav>`. You just need to create a relationship between the two elements using jump links.

For example:
```
<nav>
  <ul>
    <li><a href="#top-10-books">Description</a></li>
  </ul>
</nav>
```

Then down where you're displaying the list of the top 10 books you would create that relationship with the link by including the 'id' attribute:

```
<section id="top-10-books">
  <h2>Top 10 Books</h2>
</section>
```

The '#' means ID. We'll learn more about that in upcoming classes. Just remember for this scenario, the name 'top-10-books' has to match both in the `<nav>` and the `<section>`.

The last issue will be solved when you include the '#' within the `<a href="">` when you setup the jump links.

I hope this helps. Let me know if you have any questions.

Thanks,
Wendy

**Comment by breecousineau** [comment]
Hi @wendywarren 

Perfect! I was able to fix my errors, thank you!
